import type { CaseStudy } from "@/types/content";

export const projects: CaseStudy[] = [
  {
    title: "Arista ATS",
    slug: "arista-ats",
    kind: "Hiring",
    featured: true,
    context: "Running in production at a US-based company",
    role: "Full-stack developer",
    year: "2026",
    summary:
      "An applicant tracking and client management platform, used in production by a US company that hires global virtual assistants.",
    solution:
      "I built the whole platform on my own. Recruiters move candidates through each job's hiring steps, book interviews and send email, all in one app. AI reads each resume and scores it against the job. Once someone is hired, they move into client account management.",
    results: [
      { value: "800+", label: "candidates applied" },
      { value: "30+", label: "clients registered" },
      { value: "50+", label: "jobs posted" },
    ],
    stack: [
      "React",
      "TypeScript",
      "Zustand",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Socket.IO",
      "Tailwind CSS",
    ],
    live: "https://ats-ui-test.vercel.app/ats",
    liveLabel: "Live demo",
    demoLogin: {
      email: "demo.admin@mirtauhid.com",
      password: "Arista@Demo2026",
    },
    status: ["In production"],
    owned: "Solo build: research, design, code, AI and deployment. I still maintain it.",
    features: [
      "Drag-and-drop hiring pipeline for every job",
      "AI reads and scores resumes against each job",
      "Interview scheduling with Zoom links, scorecards and email in and out",
      "8 user roles, each with their own permissions",
    ],
    screenshots: [
      {
        label: "Landing",
        src: "/images/arista-ats-landing.webp",
        width: 2000,
        height: 1080,
        alt: "Arista ATS landing page: Hiring, organized, with an Enter workspace button",
      },
      {
        label: "Dashboard",
        src: "/images/arista-ats-dashboard.webp",
        width: 2000,
        height: 1080,
        alt: "Arista ATS dashboard with candidate, client and open job totals and application and hiring trend charts",
      },
      {
        label: "Candidates",
        src: "/images/arista-ats-candidates.webp",
        width: 2000,
        height: 1080,
        alt: "Candidates table with job applied, current stage, skills and AI score for each candidate",
      },
      {
        label: "Jobs",
        src: "/images/arista-ats-jobs-2.webp",
        width: 2000,
        height: 1080,
        alt: "Jobs list beside the details of the selected job, with salary range, skills, tags and description",
      },
      {
        label: "Client",
        src: "/images/arista-ats-client.webp",
        width: 2000,
        height: 1080,
        alt: "Client details panel with contact info, company details, tags and tabs for contacts, jobs, activity, notes and CRM",
      },
      {
        label: "Hired",
        src: "/images/arista-ats-hired.webp",
        width: 2000,
        height: 1080,
        alt: "Hired candidates table showing the job each was hired for, tags and hire date",
      },
      {
        label: "Profile",
        src: "/images/arista-ats-profile.webp",
        width: 2000,
        height: 1080,
        alt: "Candidate profile with AI score, summary, skills, certifications and work experience",
      },
    ],
  },
  {
    title: "Niblet",
    slug: "niblet",
    kind: "Nutrition",
    featured: true,
    context: "Portfolio project",
    role: "Full-stack developer",
    year: "2026",
    summary:
      "An AI nutrition coach you talk to. Say what you ate, or send a photo, and it logs the meal and does the macro maths. Set a health goal and log your weight regularly to track progress.",
    solution:
      "A chat you talk to. Say what you ate or send a photo, and the AI logs the meal, fixes mistakes and answers questions about your day. You can set a health goal and track it by logging your food and weight. I built it all on my own, from the design to the Firebase backend.",
    results: [],
    stack: ["TypeScript", "Next.js", "Tailwind CSS", "Firebase", "OpenAI API"],
    live: "https://niblet-ai.vercel.app",
    liveLabel: "Live demo",
    status: ["Live demo"],
    owned: "Solo build: design, code, the AI agent, tests and deployment.",
    features: [
      "Log by chatting: one message can log a meal and your weight",
      "Photo logging: snap your plate and get an estimate you can correct",
      "Goals and progress: set a health goal and track your weight and calories",
      "Private by design: export or delete all your data anytime",
    ],
    screenshots: [
      {
        label: "Landing",
        src: "/images/niblet-landing.webp",
        width: 2000,
        height: 1080,
        alt: "Niblet landing page: Just say what you ate, with a sample receipt-style food log",
      },
      {
        label: "Chat",
        src: "/images/niblet-chat.webp",
        width: 2000,
        height: 1080,
        alt: "Niblet chat logging a curry dinner from a photo, with a daily calorie and macro summary beside it",
      },
      {
        label: "Meals",
        src: "/images/niblet-meals.webp",
        width: 2000,
        height: 1080,
        alt: "Meal log grouped by day with calories, macros and the assumption behind each estimate",
      },
      {
        label: "Weight",
        src: "/images/niblet-weight.webp",
        width: 2000,
        height: 1080,
        alt: "Weight log with the latest weight and the change since each earlier entry",
      },
      {
        label: "Insights",
        src: "/images/niblet-insights.webp",
        width: 2000,
        height: 1080,
        alt: "Insights page with weight and calorie charts, goal progress and daily macro averages",
      },
      {
        label: "Goals",
        src: "/images/niblet-goals.webp",
        width: 2000,
        height: 1080,
        alt: "Goals tab showing weight loss progress and daily calorie and macro targets",
      },
    ],
  },
  {
    title: "Draftboard",
    slug: "draftboard",
    kind: "Productivity",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2026",
    summary: "A private sketch board that works offline, built on Excalidraw.",
    solution:
      "A board manager around the Excalidraw canvas. Boards save in the browser, export to one JSON file, and the app can be installed.",
    results: [],
    highlight: "Works offline",
    stack: ["Next.js", "TypeScript", "Excalidraw"],
    live: "https://draftboard-canvas.vercel.app",
    repo: "https://github.com/mtauhidul/draftboard",
  },
  {
    title: "CareSync",
    slug: "caresync",
    kind: "Healthcare",
    context: "",
    role: "Frontend design engineer",
    year: "2026",
    summary: "A hospital app for managing rooms, tasks, and workflows.",
    solution:
      "A staff portal with real-time room status and a separate dashboard for each role. The first version served 10k+ patients.",
    results: [],
    highlight: "v1 served 10k+ patients",
    stack: ["Next.js", "TypeScript", "Firebase"],
    live: "https://caresync-v2.vercel.app",
  },
  {
    title: "KIOSK",
    slug: "checkin-kiosk",
    kind: "Healthcare",
    context: "",
    role: "Frontend design engineer",
    year: "2025",
    summary: "A simple patient check-in app for forms and health details.",
    solution:
      "A touch-friendly app for kiosks and tablets. Patients confirm their details, photograph their ID and insurance card, fill in their medical, family, surgical and social history, sign, answer a short survey and review everything. A test mode lets it run offline as a demo.",
    results: [],
    stack: ["React", "MUI", "Cloudinary"],
    live: "https://kiosk-demo-beta.vercel.app",
  },
  {
    title: "Night Shift",
    slug: "night-shift",
    kind: "Creative",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2026",
    summary: "A lofi workspace for late-night focus, music, and calm.",
    solution:
      "A single HTML file. The view from an empty chair looking out over a rainy city at night is drawn on canvas, and the lofi beat (piano, pad, bass, melody and soft drums) is generated live with the Web Audio API.",
    results: [],
    stack: ["JavaScript", "Canvas", "Web Audio"],
    live: "https://night-lofi-anim.vercel.app",
    repo: "https://github.com/mtauhidul/night-lofi-anim",
  },
  {
    title: "MailForge AI",
    slug: "mailforge-ai",
    kind: "Landing",
    context: "Concept project",
    role: "Frontend design engineer",
    year: "2026",
    summary: "An AI email assistant landing page with light and dark themes.",
    solution:
      "A single-page landing site for an imaginary AI email assistant: hero, features, demo and pricing sections, a small design system with shared components and animation presets, scroll animations with subtle parallax, and a responsive layout with light and dark themes.",
    results: [],
    stack: ["React", "TypeScript", "Framer Motion"],
    live: "https://mail-forge-ai.vercel.app",
    repo: "https://github.com/mtauhidul/mail-forge",
  },
  {
    title: "Compliance Dashboard",
    slug: "compliance-dashboard",
    kind: "Security",
    context: "Concept project",
    role: "Frontend design engineer",
    year: "2026",
    summary: "A dashboard for tracking security findings and compliance work.",
    solution:
      "A dashboard interface designed and built from a concept, iterating in code with no mockups. It shows KPI metrics, a findings table with severity colours, framework status for SOC2, ISO27001, GDPR, HIPAA and PCI-DSS, and a control list. The UI is the focus: the data is sample data.",
    results: [],
    stack: ["Next.js", "Tailwind CSS", "TypeScript"],
    live: "https://compliance-dashboard-zeta.vercel.app",
  },
];
