import type { CaseStudy } from "@/types/content";

export const projects: CaseStudy[] = [
  {
    title: "Northwind Analytics",
    slug: "northwind-analytics",
    summary: "Real-time analytics that turned 40M weekly events into decisions.",
    featured: true,
    context: "Northwind (SaaS, Series A)",
    role: "Lead engineer",
    year: "2026",
    problem: "Reports took 9 seconds to load and the team stopped trusting the numbers.",
    solution:
      "Moved event storage to ClickHouse, built a streaming ingestion pipeline and rebuilt the dashboard with server rendering and cached aggregates.",
    results: [
      { value: "600ms", label: "report load, from 9s" },
      { value: "40M", label: "events per week" },
      { value: "-35%", label: "infra cost" },
    ],
    stack: ["Next.js", "TypeScript", "ClickHouse", "AWS"],
    live: "#",
    repo: "#",
  },
  {
    title: "Atlas Health Portal",
    slug: "atlas-health",
    summary: "Scheduling and records platform used by 14 clinics.",
    context: "Atlas Clinics",
    role: "Frontend design engineer",
    year: "2025",
    problem: "14 clinics scheduled patients by phone and spreadsheet.",
    solution:
      "Built a booking and records platform with role-based access, audit logs and reminders, to HIPAA standards.",
    results: [
      { value: "14", label: "clinics onboarded" },
      { value: "-60%", label: "no-shows" },
    ],
    stack: ["React", "Node.js", "PostgreSQL"],
    live: "#",
  },
  {
    title: "Lumen Design Kit",
    slug: "lumen-kit",
    summary: "Open-source library of 60+ accessible, themeable components.",
    context: "Open source",
    role: "Creator",
    year: "2025",
    problem: "Teams kept rebuilding the same accessible components from scratch.",
    solution:
      "Published 60+ themeable, keyboard-accessible primitives with docs and a Storybook.",
    results: [
      { value: "AA", label: "WCAG contrast" },
      { value: "60+", label: "components" },
    ],
    stack: ["Tailwind", "Radix", "Storybook"],
    live: "#",
    repo: "#",
  },
  {
    title: "Pulse Mobile Banking",
    slug: "pulse-banking",
    summary: "Cross-platform banking app with biometric sign-in.",
    context: "Pulse (fintech)",
    role: "Frontend lead",
    year: "2024",
    problem: "Onboarding took 11 steps and half of new users dropped off.",
    solution:
      "Shipped a cross-platform app with biometric auth, instant transfers and a 3-step onboarding.",
    results: [
      { value: "+48%", label: "onboarding completion" },
      { value: "4.8", label: "store rating" },
    ],
    stack: ["React Native", "GraphQL", "Node.js"],
    live: "#",
  },
  {
    title: "Orbit CLI",
    slug: "orbit-cli",
    context: "Open source",
    role: "Creator",
    year: "2024",
    summary: "Developer CLI that scaffolds, deploys and monitors services.",
    problem:
      "Setting up a new service meant copying files and running the same steps by hand.",
    solution:
      "A command-line tool that scaffolds a project, deploys it and shows its health.",
    results: [{ value: "1", label: "command to ship" }],
    stack: ["Node.js", "TypeScript", "CLI"],
    live: "#",
    repo: "#",
  },
  {
    title: "Fieldnotes",
    slug: "fieldnotes",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2024",
    summary: "A markdown notes app that keeps working offline.",
    problem: "Notes apps lose your work when the connection drops.",
    solution:
      "A local-first notes app that stores everything on the device and syncs later.",
    results: [{ value: "0", label: "lost notes" }],
    stack: ["Next.js", "IndexedDB", "PWA"],
    live: "#",
    repo: "#",
  },
  {
    title: "Ledger Lite",
    slug: "ledger-lite",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2023",
    summary: "A personal finance tracker with clear monthly reports.",
    problem: "Spreadsheets made it hard to see where money actually went.",
    solution: "A simple tracker that groups spending and shows a clear monthly summary.",
    results: [{ value: "3", label: "clicks to add an entry" }],
    stack: ["React", "Node.js", "MongoDB"],
    live: "#",
  },
];
