import type { CaseStudy } from "@/types/content";

export const projects: CaseStudy[] = [
  {
    title: "Northwind Analytics",
    slug: "northwind-analytics",
    kind: "Dashboard",
    summary: "Real-time analytics that turned 40M weekly events into decisions.",
    featured: true,
    context: "Northwind (SaaS, Series A)",
    role: "Lead engineer",
    year: "2026",
    problem: "Reports took 9 seconds to load and the team stopped trusting the numbers.",
    solution:
      "Moved event storage to ClickHouse, built a streaming ingestion pipeline and rebuilt the dashboard with server rendering and cached aggregates.",
    results: [
      { value: "600ms", label: "report load, from 9s" },
      { value: "40M", label: "events per week" },
      { value: "-35%", label: "infra cost" },
    ],
    stack: ["Next.js", "TypeScript", "ClickHouse", "AWS"],
    live: "#",
    repo: "#",
  },
  {
    title: "Draftboard",
    slug: "draftboard",
    kind: "Web app",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2026",
    summary:
      "A private sketch board that works offline. Everything stays on your device.",
    problem: "Sketch tools usually want an account and a connection.",
    solution:
      "A board manager around the Excalidraw canvas. Boards save in the browser, export to one JSON file, and the app can be installed.",
    results: [],
    stack: ["Next.js", "TypeScript", "Excalidraw"],
    live: "https://draftboard-canvas.vercel.app",
    repo: "https://github.com/mtauhidul/draftboard",
  },
  {
    title: "CareSync",
    slug: "caresync",
    kind: "Healthcare system",
    context: "",
    role: "Frontend design engineer",
    year: "2026",
    summary: "Management system with real-time room status and live dashboards.",
    problem:
      "Clinics need staff, patients and the waiting room working from the same live picture.",
    solution: "A staff portal with real-time room status and dashboards.",
    results: [],
    stack: ["Next.js", "TypeScript", "Firebase"],
    live: "https://caresync-v2.vercel.app",
  },
  {
    title: "Pulse Mobile Banking",
    slug: "pulse-banking",
    kind: "Mobile app",
    summary: "Cross-platform banking app with biometric sign-in.",
    context: "Pulse (fintech)",
    role: "Frontend lead",
    year: "2024",
    problem: "Onboarding took 11 steps and half of new users dropped off.",
    solution:
      "Shipped a cross-platform app with biometric auth, instant transfers and a 3-step onboarding.",
    results: [
      { value: "+48%", label: "onboarding completion" },
      { value: "4.8", label: "store rating" },
    ],
    stack: ["React", "GraphQL", "Node.js"],
    live: "#",
  },
  {
    title: "Orbit CLI",
    slug: "orbit-cli",
    kind: "CLI tool",
    context: "Open source",
    role: "Creator",
    year: "2024",
    summary: "Developer CLI that scaffolds, deploys and monitors services.",
    problem:
      "Setting up a new service meant copying files and running the same steps by hand.",
    solution:
      "A command-line tool that scaffolds a project, deploys it and shows its health.",
    results: [{ value: "1", label: "command to ship" }],
    stack: ["Node.js", "TypeScript", "CLI"],
    live: "#",
    repo: "#",
  },
  {
    title: "Fieldnotes",
    slug: "fieldnotes",
    kind: "Web app",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2024",
    summary: "A markdown notes app that keeps working offline.",
    problem: "Notes apps lose your work when the connection drops.",
    solution:
      "A local-first notes app that stores everything on the device and syncs later.",
    results: [{ value: "0", label: "lost notes" }],
    stack: ["Next.js", "Firebase", "PWA"],
    live: "#",
    repo: "#",
  },
  {
    title: "Ledger Lite",
    slug: "ledger-lite",
    kind: "Web app",
    context: "Personal project",
    role: "Frontend design engineer",
    year: "2023",
    summary: "A personal finance tracker with clear monthly reports.",
    problem: "Spreadsheets made it hard to see where money actually went.",
    solution: "A simple tracker that groups spending and shows a clear monthly summary.",
    results: [{ value: "3", label: "clicks to add an entry" }],
    stack: ["React", "Node.js", "MongoDB"],
    live: "#",
  },
];
